crypto

In [3]:
from alpaca.data.historical.crypto import CryptoHistoricalDataClient
from alpaca.data.requests import CryptoBarsRequest
from alpaca.data.timeframe import TimeFrame, TimeFrameUnit
import pendulum as dt
timez_zone="America/New_York"


crypto_historical_data_client = CryptoHistoricalDataClient()
req = CryptoBarsRequest(
    symbol_or_symbols = 'ETH/USD',
    timeframe=TimeFrame(amount = 1, unit = TimeFrameUnit.Day), # specify timeframe
    start = dt.datetime(2024,1,1,1,1,1,tz=timez_zone),                          # specify start datetime, default=the beginning of the current day.
    end=dt.datetime(2024,12,30,1,1,1,tz=timez_zone),                                        # specify end datetime, default=now
    # limit = 2,                                               # specify limit
)

history_df2=crypto_historical_data_client.get_crypto_bars(req).df
history_df2

                                        open       high          low  \
symbol  timestamp
ETH/USD 2024-01-02 00:00:00+00:00  2351.7125  2433.1650  2346.870000
        2024-01-03 00:00:00+00:00  2356.3110  2384.8500  2109.520500
        2024-01-04 00:00:00+00:00  2209.7590  2297.1050  2198.158623
        2024-01-05 00:00:00+00:00  2270.2900  2278.7645  2152.205000
        2024-01-06 00:00:00+00:00  2270.8135  2272.1000  2191.906259
...                                      ...        ...          ...
        2024-12-26 00:00:00+00:00  3496.7500  3511.1250  3302.450000
        2024-12-27 00:00:00+00:00  3332.6600  3437.4950  3301.661000
        2024-12-28 00:00:00+00:00  3331.3985  3421.2010  3319.153500
        2024-12-29 00:00:00+00:00  3396.8370  3407.4110  3320.766000
        2024-12-30 00:00:00+00:00  3348.4650  3430.2855  3297.665000

                                       close      volume  trade_count  \
symbol  timestamp
ETH/USD 2024-01-02 00:00:00+00:00  2355.0500  184.053015        157.0
        2024-01-03 00:00:00+00:00  2209.8000   39.799342        136.0
        2024-01-04 00:00:00+00:00  2269.6200   42.577529         89.0
        2024-01-05 00:00:00+00:00  2269.4100   10.656595         79.0
        2024-01-06 00:00:00+00:00  2241.2095    2.160901         43.0
...                                      ...         ...          ...
        2024-12-26 00:00:00+00:00  3329.4750   29.464947        128.0
        2024-12-27 00:00:00+00:00  3328.2910    7.269414        193.0
        2024-12-28 00:00:00+00:00  3397.5895   27.258470         98.0
        2024-12-29 00:00:00+00:00  3349.4080    2.875096        140.0
        2024-12-30 00:00:00+00:00  3358.6115   14.856977        275.0

                                          vwap
symbol  timestamp
ETH/USD 2024-01-02 00:00:00+00:00  2386.636212
        2024-01-03 00:00:00+00:00  2246.166738
        2024-01-04 00:00:00+00:00  2249.682364
        2024-01-05 00:00:00+00:00  2242.161777
        2024-01-06 00:00:00+00:00  2237.023847
...                                        ...
        2024-12-26 00:00:00+00:00  3340.559412
        2024-12-27 00:00:00+00:00  3353.847703
        2024-12-28 00:00:00+00:00  3341.486985
        2024-12-29 00:00:00+00:00  3360.428510
        2024-12-30 00:00:00+00:00  3383.500181

[364 rows x 7 columns]